name: Compile, Test, and Deploy

on:
  pull_request: {}
  push:
    branches:
      - main
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  run-python-tests:
    strategy:
      matrix:
        python-version:
#           - '3.7'
          - '3.8'
#           - '3.9'
#           - '3.10'
#           - '3.11'
        # TODO: Switch back to macos-latest once https://github.com/actions/python-versions/pull/114 is fixed
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          submodules: recursive
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y pkg-config 
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r dev-requirements.txt
      - name: Run profiling
        run: "asv continuous ${{ github.ref }} master"
